### ISSUE TITLE
Receiving data with curl

### ISSUE THREAD

**Issue by ozdemircili** [mikechau/titanium_edge#1]
Hi,

Im trying to send data to Top 10 Instruments widget yet get a 204.

The curl Im using is the following;

 curl -d '{ "auth_token":"YOUR_AUTH_TOKEN", "series": [{ "name":"NAME", "data":"9" }], "catagories": "list0", "color" : "#2c3e50" }' http://localhost:3030/widgets/horizonbarstack

What would be the correct way to send data?

Thanks in advance

**Comment by mikechau** [comment]
Hi there! Let me first apologize for the delayed response.

It should look like this:

``` shell
curl -d '{ "auth_token": "YOUR_AUTH_TOKEN", "series":[{"name":"Instruments", "data":[983,711,233] }], "categories":["one","two","three"], "color": "#2c3e50"}' \http://localhost:3030/widgets/top_instruments
```

When sending data via curl, the url needs to match the widget data-id name. If you look inside `dashing/edge.erb`:

``` html
<li data-row="1" data-col="1" data-sizex="2" data-sizey="1">
  <div data-id="top_instruments" data-view="Horizonbarstack" data-title="Top 10 Instruments" style="background-color:#2c3e50;"></div>
</li>
```

You can see the widget is called `top_instruments`, but it is using the widget `Horizonbarstack`.

Hope this helps!
