### ISSUE TITLE
Does not create log file

### ISSUE THREAD

**Issue by ozdemircili** [mikechau/titanium_edge#2]
Hi,

Dashing start does not create a log file while the original version creates a log file in the mail directory and writes thin.log.

How can we get back the log file?

**Comment by mikechau** [comment]
Hi!

I am not sure how to get it back, I don't believe dashing ever created a log file but you should be able to pipe the output into a text file.

`dashing start > log 2>&1`

I would bring up a issue at https://github.com/Shopify/dashing/issues?state=open

Cheers!
