### ISSUE TITLE
Importing SQL Data

### ISSUE THREAD

**Issue by MartynKeigher** [mikechau/titanium_edge#4]
Hey guys....

I'm looking to use the following widgets http://i.imgur.com/kcomybL.jpg to display results of a MySQL Query. I'm currently using the "List" widget from the original Dashing, and currently it's working fine. - but i want to spice up my dashboard a little with these new widgets.

My SQL query returns 2 columns. Applications + Count, and each SQL query lives in its own *.rb file in the jobs folder (for sake of keeping it simple!)

Could you please show me how I would construct a job file so that the data would display correctly in the widgets I have shown in the screenshot above?

Here is an example of a current job file, that I would display using the list widget...

```
require_relative 'my_db.rb'

SCHEDULER.every '30s', :first_in => 0 do |job|

        db = MyDb.conn

        sql = "SELECT clients.name AS 'Client', COUNT(*) AS count  FROM clients, computers WHERE computers.clientid=clients.clientid AND (((Computers.Flags & 1024) = 1024)) AND `OS` LIKE '%server%' GROUP BY clients.name ORDER BY COUNT DESC LIMIT 5"

  results = db.query(sql)

  acctitems = results.map do |row|
    row = {
      :label => row['Client'],
      :value => row['count']
    }
  end

  send_event('ninitelist' , { items: acctitems } )

end
```

@tschew72 - I see you have been doing some great work on this lately! What is the best method for 'merging' your code changes into my current Dashing install?; or, are there some instructions on it anywhere I'm missing??

Thanks yo so much for your help!!

Martyn

**Comment by mikechau** [comment]
Hi @MartynKeigher,

To use the `Top Exchanges` widget, it requires the following:
- `data`: The actual data points. This is an `array` of numbers.
- `categories`: The names of the data points you are sending, this is an `array` of strings.

``` ruby
your_data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
your_categories = ['data_point_1_name', 'data_point_2_name', ...]
```

After you have created you've generated your data, you can just call...

``` ruby
send_event('data-id-name', {
  series: [{
    data: your_data
  }],
  categories: your_categories,
  color: '#efad1b'
})
```

To implement it in your html, it looks like this:

``` html
<li data-row="1" data-col="1" data-sizex="2" data-sizey="1">
    <div data-id="top_exchanges" data-view="Highbar" data-title="Transactions by Exchange" style="background-color:#efad1b;"></div>
</li>
```

`data-id-name` can be set to whatever you want, and when you use `send_event`, that `data-id-name` will be your first argument. `data-view` represents the widget name.

If you need to modify the widget, the relevant files are inside `widgets/highbar`.

---

To use the `Top 10 Instruments` widget, it requires the following:
- `name`: Represents the name of the data being sent (I think it shows up in tooltip).
- `data`: The actual data points. This is an `array` of numbers.
- `categories`: The names of the the data points you are sending, this is an `array` of strings.
- `color`: The chart background color.

``` ruby
your_data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
your_categories = ['data_point_1_name', 'data_point_2_name', ...]
```

After you have created you've generated your data, you can just call...

``` ruby
send_event('data-id-name', {
  series: [{
    name: 'Chart Title',
    data: your_data
  }],
  categories: your_categories,
  color: '#2c3e50'
})
```

To implement it in your html, it looks like this:

``` html
<li data-row="1" data-col="1" data-sizex="2" data-sizey="1">
   <div data-id="data-id-name" data-view="Horizonbarstack" data-title="Top 10 Instruments" style="background-color:#2c3e50;"></div>
</li>
```

`data-id-name` can be set to whatever you want, and when you use `send_event`, that `data-id-name` will be your first argument. `data-view` represents the widget name.

If you need to modify the widget, the relevant files are inside `widgets/horizonbarstack`.

---

`jobs/charts_data.rb` has some more examples.

Also, I've been meaning to rewrite this.. when I made this a year ago, I did not know much about coffeescript. Anyways, I hope this helps!

Btw, you can also integrate `ActiveRecord` pretty easily, if you prefer to interact with your database via a `orm`, here's an example: https://github.com/maxxst/dashing_active_record

**Comment by MartynKeigher** [comment]
Hey @mikechau, 

Thank you very much for your detailed breakdown (and prompt answer!!) ... definitely answers a few other questions I thought of, AFTER I posted my initial question! ;)

As for my SQL query, returning results... I was playing around with your code for a bit today and I notice that right now, it using a CSV to pull data.

What would be the best way to build a dedicated .rb file in the jobs folder for the 'HorizonBarStack' widget. You can see how I'm using my my_db.rb file as the 'odbc conenction' and then displaying 2 columns on the LIST widget. A live instance of my current dash is here: http://dash.managedservic.es:3030 

FYI... I started a repo for my project that is built on the Dashing framework here: https://github.com/LabTechGeek/Dashing-Project so you can see how I'm pulling in data to my main dashboard located at `dashboard/home.erb`.

Thanks.

PS: As for the re-write... Was you looking to update to code and/or ADD more features?

**Comment by mikechau** [comment]
@MartynKeigher,

You can build it like you would any job, how you are doing it is fine, run your query, after that you need to create two arrays, and pass in the data as I demonstrated above. The first being the actual data points and the second being the labels for those data points.

Yeah, I will probably clean up the coffeescript and update highcharts and fix the styling issues on Firefox. I think I've figured how to make it load saved data from `history.yml` on initial load as described [here](https://github.com/Shopify/dashing/issues/204). But I have not really had the time to.
